### ISSUE TITLE
Weather entity still contains forecast attribute

### ISSUE THREAD

**Issue by kaizersoje** [mawinkler/astroweather#34]
I noticed that after upgrading to v0.23.2, the weather attribute still contains the forecast attribute. I am not sure if the weather entity should contain the forecast attribute, unless I am mistaken.

![image](https://github.com/mawinkler/astroweather/assets/54566217/4c765e8f-d32d-4a58-83d2-c3dc8e08d158)

I also noticed the `manifest.json` file shows the version as `0.23.1`

![image](https://github.com/mawinkler/astroweather/assets/54566217/bf0f193e-1dc7-4c03-882e-4d5aae3e83f3)

**Comment by mawinkler** [comment]
First - Yes I know. It's because the lovelace card still uses the forecast attribute and I wasn't able to figure out how I can call the service from the card. Quickly checking other weather integrations like OpenWeatherMap and Deutscher Wetterdienst all have the attribute still enabled. Did you find any example of a proper lovelace card using the new service?

Second, uups - I always forget to update the version in the one or the other place. Will correct it, thanks.

**Comment by mawinkler** [comment]
Fixed with release [0.50.0](https://github.com/mawinkler/astroweather/releases/tag/v0.50.0).
